# scribe fish completions
# Generated by `scribe completions fish` — do not edit by hand.

# Disable file completions for scribe globally; each subcommand re-enables
# or restricts completions explicitly.
complete -c scribe -f

# ── top-level subcommands ─────────────────────────────────────────────────────
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a project    -d 'Manage projects'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a task       -d 'Manage tasks'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a todo       -d 'Manage todos'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a track      -d 'Time tracking'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a capture    -d 'Quickly capture a thought into the inbox'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a inbox      -d 'Manage the quick-capture inbox'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a reminder   -d 'Manage reminders'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a setup      -d 'First-run wizard and setup status'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a service    -d 'Manage the background daemon service'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a daemon     -d 'Run the background reminder daemon'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a agent      -d 'Install skill files for AI coding agents'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a completions -d 'Print a shell completion script for the given shell'
complete -c scribe -n 'not __fish_seen_subcommand_from project task todo track capture inbox reminder setup service daemon agent completions help' \
  -a help       -d 'Print this message or the help of the given subcommand(s)'

# ── global flags ──────────────────────────────────────────────────────────────
complete -c scribe -l help    -s h -d 'Print help'
complete -c scribe -l version -s V -d 'Print version'

# ── project subcommands ───────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a add     -d 'Create a new project'
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a list    -d 'List projects'
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a show    -d 'Show details of a project'
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a edit    -d 'Edit a project fields'
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a archive -d 'Archive a project and all its items'
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a restore -d 'Restore an archived project'
complete -c scribe -n '__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from add list show edit archive restore delete help' \
  -a delete  -d 'Delete a project (must be empty or archived first)'

# project add
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from add' \
  -l name   -d 'Human-readable project name' -r
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from add' \
  -l desc   -d 'Optional project description' -r
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from add' \
  -l output -d 'Output format' -r -a 'text json'

# project list
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list' \
  -l status   -d 'Filter by status' -r -a 'active paused completed'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list' \
  -l output   -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list' \
  -l archived -d 'Include archived projects'

# project show / edit / archive / restore / delete — slug argument
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from show' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from show' \
  -a '(scribe __complete projects 2>/dev/null)' -d 'Project slug'

complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit' \
  -l new-slug -d 'New slug' -r
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit' \
  -l name     -d 'New name' -r
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit' \
  -l desc     -d 'New description' -r
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit' \
  -l status   -d 'New status' -r -a 'active paused completed'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit' \
  -l output   -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit' \
  -a '(scribe __complete projects 2>/dev/null)' -d 'Project slug'

complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from archive' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from archive' \
  -a '(scribe __complete projects 2>/dev/null)' -d 'Project slug'

complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from restore' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from restore' \
  -a '(scribe __complete projects 2>/dev/null)' -d 'Project slug'

complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete' \
  -a '(scribe __complete projects 2>/dev/null)' -d 'Project slug'

# ── task subcommands ──────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a add     -d 'Create a new task'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a list    -d 'List tasks'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a show    -d 'Show details of a task'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a edit    -d 'Edit a task fields'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a move    -d 'Move a task to a different project'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a done    -d 'Mark a task as done'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a archive -d 'Archive a task'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a restore -d 'Restore an archived task'
complete -c scribe -n '__fish_seen_subcommand_from task; and not __fish_seen_subcommand_from add list show edit move done archive restore delete help' \
  -a delete  -d 'Delete a task'

# task add
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from add' \
  -l project  -d 'Project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from add' \
  -l priority -d 'Task priority' -r -a 'low medium high urgent'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from add' \
  -l due      -d 'Due date in YYYY-MM-DD format' -r
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from add' \
  -l output   -d 'Output format' -r -a 'text json'

# task list
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from list' \
  -l project  -d 'Filter by project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from list' \
  -l status   -d 'Filter by status' -r -a 'todo in_progress done cancelled'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from list' \
  -l priority -d 'Filter by priority' -r -a 'low medium high urgent'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from list' \
  -l output   -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from list' \
  -l archived -d 'Include archived tasks'

# task show
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from show' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from show' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# task edit
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from edit' \
  -l title    -d 'New title' -r
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from edit' \
  -l status   -d 'New status' -r -a 'todo in_progress done cancelled'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from edit' \
  -l priority -d 'New priority' -r -a 'low medium high urgent'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from edit' \
  -l due      -d 'New due date' -r
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from edit' \
  -l output   -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from edit' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# task move
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from move' \
  -l project -d 'Destination project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from move' \
  -l output  -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from move' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# task done
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from done' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from done' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# task archive
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from archive' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from archive' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# task restore
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from restore' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from restore' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# task delete
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from delete' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from task; and __fish_seen_subcommand_from delete' \
  -a '(scribe __complete tasks 2>/dev/null)' -d 'Task slug'

# ── todo subcommands ──────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a add     -d 'Create a new todo'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a list    -d 'List todos'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a show    -d 'Show details of a todo'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a move    -d 'Move a todo to a different project'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a done    -d 'Mark a todo as done'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a archive -d 'Archive a todo'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a restore -d 'Restore an archived todo'
complete -c scribe -n '__fish_seen_subcommand_from todo; and not __fish_seen_subcommand_from add list show move done archive restore delete help' \
  -a delete  -d 'Delete a todo (must be archived first)'

# todo add
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from add' \
  -l project -d 'Project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from add' \
  -l output  -d 'Output format' -r -a 'text json'

# todo list
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from list' \
  -l project  -d 'Filter by project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from list' \
  -l output   -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from list' \
  -l all      -d 'Include done todos'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from list' \
  -l archived -d 'Show archived todos instead'

# todo show
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from show' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from show' \
  -a '(scribe __complete todos 2>/dev/null)' -d 'Todo slug'

# todo move
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from move' \
  -l project -d 'Destination project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from move' \
  -l output  -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from move' \
  -a '(scribe __complete todos 2>/dev/null)' -d 'Todo slug'

# todo done
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from done' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from done' \
  -a '(scribe __complete todos 2>/dev/null)' -d 'Todo slug'

# todo archive
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from archive' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from archive' \
  -a '(scribe __complete todos 2>/dev/null)' -d 'Todo slug'

# todo restore
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from restore' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from restore' \
  -a '(scribe __complete todos 2>/dev/null)' -d 'Todo slug'

# todo delete
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from delete' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from todo; and __fish_seen_subcommand_from delete' \
  -a '(scribe __complete todos 2>/dev/null)' -d 'Todo slug'

# ── track subcommands ─────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from track; and not __fish_seen_subcommand_from start stop status report help' \
  -a start  -d 'Start a new timer'
complete -c scribe -n '__fish_seen_subcommand_from track; and not __fish_seen_subcommand_from start stop status report help' \
  -a stop   -d 'Stop the running timer'
complete -c scribe -n '__fish_seen_subcommand_from track; and not __fish_seen_subcommand_from start stop status report help' \
  -a status -d 'Show the current timer status'
complete -c scribe -n '__fish_seen_subcommand_from track; and not __fish_seen_subcommand_from start stop status report help' \
  -a report -d 'Show a time report'

# track start
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from start' \
  -l project -d 'Project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from start' \
  -l task    -d 'Task slug' -r -a '(scribe __complete tasks 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from start' \
  -l note    -d 'Optional free-text note' -r
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from start' \
  -l output  -d 'Output format' -r -a 'text json'

# track stop
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from stop' \
  -l output -d 'Output format' -r -a 'text json'

# track status
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from status' \
  -l output -d 'Output format' -r -a 'text json'

# track report
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from report' \
  -l project -d 'Filter by project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from report' \
  -l output  -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from report' \
  -l today   -d 'Restrict to today entries'
complete -c scribe -n '__fish_seen_subcommand_from track; and __fish_seen_subcommand_from report' \
  -l week    -d 'Restrict to this week entries'

# ── capture ───────────────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from capture' \
  -l output -d 'Output format' -r -a 'text json'

# ── inbox subcommands ─────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from inbox; and not __fish_seen_subcommand_from list process help' \
  -a list    -d 'List unprocessed inbox items'
complete -c scribe -n '__fish_seen_subcommand_from inbox; and not __fish_seen_subcommand_from list process help' \
  -a process -d 'Process an inbox item interactively'

# inbox list
complete -c scribe -n '__fish_seen_subcommand_from inbox; and __fish_seen_subcommand_from list' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from inbox; and __fish_seen_subcommand_from list' \
  -l all    -d 'Include already-processed items'

# inbox process
complete -c scribe -n '__fish_seen_subcommand_from inbox; and __fish_seen_subcommand_from process' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from inbox; and __fish_seen_subcommand_from process' \
  -a '(scribe __complete captures 2>/dev/null)' -d 'Capture slug'

# ── reminder subcommands ──────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from reminder; and not __fish_seen_subcommand_from add list show archive restore delete help' \
  -a add     -d 'Create a new reminder'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and not __fish_seen_subcommand_from add list show archive restore delete help' \
  -a list    -d 'List reminders'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and not __fish_seen_subcommand_from add list show archive restore delete help' \
  -a show    -d 'Show details of a reminder'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and not __fish_seen_subcommand_from add list show archive restore delete help' \
  -a archive -d 'Archive a reminder'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and not __fish_seen_subcommand_from add list show archive restore delete help' \
  -a restore -d 'Restore an archived reminder'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and not __fish_seen_subcommand_from add list show archive restore delete help' \
  -a delete  -d 'Delete a reminder (must be archived first)'

# reminder add
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from add' \
  -l project -d 'Owning project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from add' \
  -l at      -d 'When the reminder should fire (flexible datetime format)' -r
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from add' \
  -l task    -d 'Optional linked task slug' -r -a '(scribe __complete tasks 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from add' \
  -l message -d 'Optional message text' -r
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from add' \
  -l persistent -d 'Stay until dismissed (blocking alert on macOS)'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from add' \
  -l output  -d 'Output format' -r -a 'text json'

# reminder list
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from list' \
  -l project  -d 'Filter by project slug' -r -a '(scribe __complete projects 2>/dev/null)'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from list' \
  -l output   -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from list' \
  -l archived -d 'Include archived reminders'

# reminder show
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from show' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from show' \
  -a '(scribe __complete reminders 2>/dev/null)' -d 'Reminder slug'

# reminder archive
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from archive' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from archive' \
  -a '(scribe __complete reminders 2>/dev/null)' -d 'Reminder slug'

# reminder restore
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from restore' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from restore' \
  -a '(scribe __complete reminders 2>/dev/null)' -d 'Reminder slug'

# reminder delete
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from delete' \
  -l output -d 'Output format' -r -a 'text json'
complete -c scribe -n '__fish_seen_subcommand_from reminder; and __fish_seen_subcommand_from delete' \
  -a '(scribe __complete reminders 2>/dev/null)' -d 'Reminder slug'

# ── agent subcommands ─────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from agent; and not __fish_seen_subcommand_from install help' \
  -a install -d 'Install the Scribe skill file to all detected agent directories'

complete -c scribe -n '__fish_seen_subcommand_from agent; and __fish_seen_subcommand_from install' \
  -l output -d 'Output format' -r -a 'text json'

# ── setup ─────────────────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from setup' \
  -l wizard  -d 'Always run the interactive wizard'
complete -c scribe -n '__fish_seen_subcommand_from setup' \
  -l status  -d 'Show setup status and exit'

# ── service subcommands ───────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from service; and not __fish_seen_subcommand_from install uninstall status help' \
  -a install   -d 'Install and start the background daemon service'
complete -c scribe -n '__fish_seen_subcommand_from service; and not __fish_seen_subcommand_from install uninstall status help' \
  -a uninstall -d 'Stop and remove the background daemon service'
complete -c scribe -n '__fish_seen_subcommand_from service; and not __fish_seen_subcommand_from install uninstall status help' \
  -a status    -d 'Show whether the daemon service is installed'

# ── daemon ────────────────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from daemon' \
  -l interval -s i -d 'Polling interval in seconds' -r

# ── completions ───────────────────────────────────────────────────────────────
complete -c scribe -n '__fish_seen_subcommand_from completions' \
  -a 'bash zsh fish elvish powershell' -d 'Shell'
